name: travel_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_auth: ^4.16.1
  cloud_firestore: ^4.15.1
  google_maps_flutter: ^2.2.6
  intl: ^0.18.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/icon.png
    - assets/images/default-avatar.jpg
    - assets/images/djerba.jpg
    - assets/images/sahara.jpg
    - assets/images/sidi_bou_said.jpg
    - assets/images/tunis_medina.jpg


